Garbage collection finally caused a problem
del trainer caused an issue


Traceback (most recent call last):
  File "/home/rabyj/project-rabyj/sources/epi_ml/src/python/epiatlas_training.py", line 364, in <module>
    main()
  File "/home/rabyj/project-rabyj/sources/epi_ml/src/python/epiatlas_training.py", line 177, in main
    do_one_experiment(
  File "/home/rabyj/project-rabyj/sources/epi_ml/src/python/epiatlas_training.py", line 318, in do_one_experiment
    logger.experiment.log_metric("Last epoch", my_model.current_epoch, step=split_nb)
  File "/lustre07/scratch/rabyj/envs/epilap/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 198, in current_epoch
    return self.trainer.current_epoch if self.trainer else 0
ReferenceError: weakly-referenced object no longer exists